ecommerce_project:
  outputs:
    dev:
      dataset: transformed_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/dags/dbt/ecommerce_project/key_file/farhan-project.json
      location: US
      method: service-account
      priority: interactive
      project: farhan-project-434204
      threads: 1
      type: bigquery
  target: dev

  # /mnt/e/ELT_My_Project/elt_project/dags/dbt/ecommerce_project/key_file/farhan-project-434204-7c30fa209b8e.json
  # /usr/local/airflow/dags/dbt/ecommerce_projec/key_file/farhan-project-434204-7c30fa209b8e.json
